#!/bin/bash

arg1=$1
arg2=$2
arg3=$3

workingDirectory=$PWD
envsPath=$workingDirectory

py_exe=
fox_path=
bridge=

source ./path_settings

if [ -n "$py_envs" ]
then
    envsPath=$workingDirectory/$py_envs
    arg5=$envsPath
fi

if [ -z ${arg1+x} ]
then
    arg1="info"
fi

if [ -z ${arg2+x} ]
then
    arg2="None"
fi

if [ -z ${arg3+x} ]
then
    arg3="None"
fi

if [ -z ${VIRTUAL_ENV+x} ]
then
    arg4="__VIRTUAL_ENV_VARIABLE_NOT_DEFINED__"
fi

if [ -n "$py_exe" ] && [ -n "$bridge" ]:
then
    bridge=$fox_path/"brdige.py"
    $py_exe $bridge $arg1 $arg2 $arg3 $arg4 $arg5
fi

if [ -n "$arg1" ]
then
    if [ $arg1 == "activate" ]
    then
        source $envsPath/$arg2/bin/activate
    elif [ $arg1 == "deactivate" ]
    then
        deactivate
    fi 
fi




# if [ $command == activate ]
# then
#     source $envsPath/$name/bin/activate
# elif [ $command == create ]
# then
#     [ ! -d "$envsPath/$name" ] && virtualenv $envsPath/$name
# elif [ $command == remove ]
# then
#     [ -d "$envsPath/$name" ] && rm -r $envsPath/$name
# elif [ $command == install ]
# then
#     if [ -n "$VIRTUAL_ENV" ]
#     then
#         pip install $name --no-cache-dir
#     fi
# fi
