#!/usr/bin/bash

#sed -i.bak s/$'\r'//g ./path_settings

arg1=$1
arg2=$2
arg3=$3

if [ -z ${arg1} ]
then
    arg1="info"
fi

if [ -z ${arg2} ]
then
    arg2="__none__"
fi

if [ -z ${arg3} ]
then
    arg3="__none__"
fi

if [ -z ${VIRTUAL_ENV} ]
then
    VIRTUAL_ENV="__none__"
fi

workingDirectory=$PWD

. $workingDirectory/path_settings.foxy

if [ -n ${py_envs} ]
then
    py_envs=$workingDirectory$py_envs
else
    py_envs=$workingDirectory
fi

if [ -n ${fox_path} ] && [ -n ${py_exe} ]
then
    echo $arg1 
    echo $arg2
    echo $arg3
    echo $VIRTUAL_ENV
    echo $py_envs
    $py_exe $fox_path $arg1 $arg2 $arg3 $VIRTUAL_ENV $py_envs
fi

if [ $arg1 == "activate" ]
then
    source $py_envs/$arg2/bin/activate
elif [ $arg1 == "deactivate" ]
then
    deactivate
fi 

