#!/bin/bash

command=$1
name=$2

mountPath="/home/mount"

if [ $command == activate ]
then
    source $mountPath/$name/bin/activate
elif [ $command == create ]
then
    [ ! -d "$mountPath/$name" ] && virtualenv $mountPath/$name
elif [ $command == remove ]
then
    [ -d "$mountPath/$name" ] && rm -r $mountPath/$name
fi
