#!/bin/bash

command=$1
name=$2

mountPath="/home/mount"


if [ $command == activate ]
then
    if [ -z ${activeEnv+x} ] || [ $activeEnv == False ]
    then
        source $mountPath/$name/bin/activate
        activeEnv="True"
    fi
elif [ $command == deactivate ]
then
    deactivate
    activeEnv="False"
fi


